source "https://www.rubygems.org"

gem 'sinatra'
gem 'activerecord', :require => 'active_record'
gem 'sinatra-activerecord', :require => 'sinatra/activerecord'
gem 'rake'
gem 'thin'
gem 'shotgun'
gem 'rails'
gem 'pry'
gem 'nokogiri'
gem 'twilio-ruby'
gem 'require_all'
gem 'geocoder'
gem 'sqlite3'
gem 'pg'